### ISSUE TITLE
Animation velocity too slow

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#27]
For some unknown reason, the velocity of the animation when the sound is fading is slower than desired and in other platforms. This has only been tested in the simulator though.

**Comment by Oscar-Rodrigues** [comment]
What about the frame rate?

No dia 10/01/2015, às 18:05, Nuno H. <notifications@github.com> escreveu:

**Comment by nunoh** [comment]
The frame rate is set to 60 fps as in the other platforms and it draws (in the simulator at least) at a different speed, rather slower. Maybe in an iPhone itself is ok. Can you test that? ;)

**Comment by nunoh** [comment]
@Oscar-Rodrigues, please check this tomorrow on your iPhone :smile:

**Comment by nunoh** [comment]
I checked the actual frame rate being drawn and surprise surprise **it's going stupidly slow on iOS devices**. This is happening even though being set to 60 in `setup()`, which means that there's something really computing intensive going on that shouldn't. 

__OSX__
~60fps in intro and ~60 in day background, perfect.

__iOS simulator (iphone 5s 7.1)__
30fps in intro and around **11-12fps** in the day background playing sounds.

__iPad Digitopia (ios 5.1)__
60fps in intro and **<5!** in the day background playing sounds.

__Android__
just like OSX, ~60 in both cases, perfect too

Not really sure why this might be happening, the low values in the iOS simulator being kind of an alarming problem, since for sure it's not just because the iPad is "old". It might be somehow related with the management of pointers for the sounds, should double check that.
