### ISSUE TITLE
Auto orientation not working in iPad

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#30]

**Comment by nunoh** [comment]
Delaying this issue until new version of OpenFrameworks comes out (supposedly), since it will most probably resolve it already by itself. There are some suggestion on how to fix this in the OF issues and forum. However, I've tried those and none seem to work. That could be because of the already weird code there is in the `update()` method to draw correctly the screen on iOS 8.

**Comment by nunoh** [comment]
Removing `pending` label here too, since of `0.9.0` is out too

**Comment by nunoh** [comment]
@Oscar-Rodrigues What's the status of this? Didn't you close this the other day?

**Comment by Oscar-Rodrigues** [comment]
Yes. From my testing this is solved. Closing!
