### ISSUE TITLE
Status bar should be hidden

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#33]
<img width="670" alt="screen shot 2015-07-21 at 17 23 26" src="https://cloud.githubusercontent.com/assets/1161423/8806167/4363fb4c-2fcd-11e5-99b6-f3d294df2666.png">

**Comment by Oscar-Rodrigues** [comment]
@nunoh , is this still happening? I no longer have this problem, so I'm closing it. Tested on iPhone, iPad and various simulators.

**Comment by nunoh** [comment]
I also double checked, but nope, not getting this anymore. Nice :+1:
