### ISSUE TITLE
Mac app version

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#34]
What about releasing this under the Mac App Store itself? Should be easy. There is a guide for that:

http://nickhardeman.com/591/preparing-an-openframeworks-application-for-the-mac-app-store/

**Comment by Oscar-Rodrigues** [comment]
This is a good question, but I'm not sure it's our best option. Downloading from the app store would link the app directly to an account (which can lead to problems, [see here](https://discussions.apple.com/thread/4025775?start=0&tstart=0) for an example) and, most likely, prevent us from having it as a download on our website, though I'm not sure. Should we leave it for discussion on the next meeting?

**Comment by nunoh** [comment]
Sounds good :+1:

**Comment by Oscar-Rodrigues** [comment]
As discussed in the meeting, this is not relevant for the moment. We are opting for our own distribution. Closing.
