### ISSUE TITLE
Make it compile in Android with OF 0.9

### ISSUE THREAD

**Issue by nunoh** [Digitopia/PORTOphone-app#35]
OF 0.9 now supports both Android Studio and Eclipse. Since we had so many problems with Eclipse in the past (and also because it has been officially deprecated) trying first to compile it with Android Studio.

- [x] update [Java for OSX](https://support.apple.com/kb/DL1572?locale=en_US)
- [x] update Android Studio
- [x] update all SDK manager dependencies
- [x] update to NDK version [`r10e`](http://developer.android.com/ndk/downloads/index.html) (note that there are special instructions to unarchive the downloaded file in the link).
- [x] follow the [official setup](http://openframeworks.cc/setup/android-studio/) procedure for Android Studio for OF
- [x] successfully compile and run some random example on device
- [x] compile PORTOphone on simulator
- [x] compile PORTOphone on device

**Comment by nunoh** [comment]
@Oscar-Rodrigues Please try to run Android yourself and close this when finish.

**Comment by Oscar-Rodrigues** [comment]
Success! Closing :)

**Comment by nunoh** [comment]
Niiice :+1:
